# Generated by Django 3.1 on 2020-08-28 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bugs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='markedBy',
            field=models.CharField(default='NONE', max_length=240),
        ),
    ]
