# Generated by Django 3.1 on 2020-08-28 15:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bugs', '0002_ticket_markedby'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='date',
            field=models.DateTimeField(default=datetime.date(2020, 8, 28)),
        ),
    ]
