# Generated by Django 3.1 on 2020-08-28 15:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bugs', '0003_auto_20200828_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
