# Generated by Django 3.1 on 2020-08-26 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bugs', '0006_auto_20200826_1836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('NEW', 'New'), ('IN PROGRESS', 'In Progess'), ('DONE', 'Done'), ('INVALID', 'Invalid')], default='NEW', max_length=200),
        ),
    ]
